export type CountryOption = {
  code: string;
  name: string;
  maxLength: number;
  iso: string;
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: '+93', name: 'Afghanistan', maxLength: 9, iso: 'af' },
  { code: '+355', name: 'Albania', maxLength: 9, iso: 'al' },
  { code: '+213', name: 'Algeria', maxLength: 9, iso: 'dz' },
  { code: '+1-684', name: 'American Samoa', maxLength: 7, iso: 'as' },
  { code: '+376', name: 'Andorra', maxLength: 9, iso: 'ad' },
  { code: '+244', name: 'Angola', maxLength: 9, iso: 'ao' },
  { code: '+1-264', name: 'Anguilla', maxLength: 7, iso: 'ai' },
  { code: '+672', name: 'Antarctica', maxLength: 9, iso: 'aq' },
  { code: '+1-268', name: 'Antigua and Barbuda', maxLength: 7, iso: 'ag' },
  { code: '+54', name: 'Argentina', maxLength: 10, iso: 'ar' },
  { code: '+374', name: 'Armenia', maxLength: 8, iso: 'am' },
  { code: '+297', name: 'Aruba', maxLength: 7, iso: 'aw' },
  { code: '+61', name: 'Australia', maxLength: 9, iso: 'au' },
  { code: '+43', name: 'Austria', maxLength: 10, iso: 'at' },
  { code: '+994', name: 'Azerbaijan', maxLength: 9, iso: 'az' },
  { code: '+1-242', name: 'Bahamas', maxLength: 7, iso: 'bs' },
  { code: '+973', name: 'Bahrain', maxLength: 8, iso: 'bh' },
  { code: '+880', name: 'Bangladesh', maxLength: 10, iso: 'bd' },
  { code: '+1-246', name: 'Barbados', maxLength: 7, iso: 'bb' },
  { code: '+375', name: 'Belarus', maxLength: 9, iso: 'by' },
  { code: '+32', name: 'Belgium', maxLength: 9, iso: 'be' },
  { code: '+501', name: 'Belize', maxLength: 7, iso: 'bz' },
  { code: '+229', name: 'Benin', maxLength: 8, iso: 'bj' },
  { code: '+1-441', name: 'Bermuda', maxLength: 7, iso: 'bm' },
  { code: '+975', name: 'Bhutan', maxLength: 8, iso: 'bt' },
  { code: '+591', name: 'Bolivia', maxLength: 8, iso: 'bo' },
  { code: '+387', name: 'Bosnia and Herzegovina', maxLength: 8, iso: 'ba' },
  { code: '+267', name: 'Botswana', maxLength: 8, iso: 'bw' },
  { code: '+55', name: 'Brazil', maxLength: 11, iso: 'br' },
  { code: '+246', name: 'British Indian Ocean Territory', maxLength: 7, iso: 'io' },
  { code: '+673', name: 'Brunei Darussalam', maxLength: 7, iso: 'bn' },
  { code: '+359', name: 'Bulgaria', maxLength: 9, iso: 'bg' },
  { code: '+226', name: 'Burkina Faso', maxLength: 8, iso: 'bf' },
  { code: '+257', name: 'Burundi', maxLength: 8, iso: 'bi' },
  { code: '+855', name: 'Cambodia', maxLength: 9, iso: 'kh' },
  { code: '+237', name: 'Cameroon', maxLength: 9, iso: 'cm' },
  { code: '+1', name: 'Canada', maxLength: 10, iso: 'ca' },
  { code: '+238', name: 'Cape Verde', maxLength: 7, iso: 'cv' },
  { code: '+1-345', name: 'Cayman Islands', maxLength: 7, iso: 'ky' },
  { code: '+236', name: 'Central African Republic', maxLength: 8, iso: 'cf' },
  { code: '+235', name: 'Chad', maxLength: 8, iso: 'td' },
  { code: '+56', name: 'Chile', maxLength: 9, iso: 'cl' },
  { code: '+86', name: 'China', maxLength: 11, iso: 'cn' },
  { code: '+61', name: 'Christmas Island', maxLength: 9, iso: 'cx' },
  { code: '+61', name: 'Cocos (Keeling) Islands', maxLength: 9, iso: 'cc' },
  { code: '+57', name: 'Colombia', maxLength: 10, iso: 'co' },
  { code: '+269', name: 'Comoros', maxLength: 7, iso: 'km' },
  { code: '+242', name: 'Congo', maxLength: 9, iso: 'cg' },
  { code: '+243', name: 'Congo, Democratic Republic', maxLength: 9, iso: 'cd' },
  { code: '+682', name: 'Cook Islands', maxLength: 5, iso: 'ck' },
  { code: '+506', name: 'Costa Rica', maxLength: 8, iso: 'cr' },
  { code: '+225', name: "Côte d'Ivoire", maxLength: 8, iso: 'ci' },
  { code: '+385', name: 'Croatia', maxLength: 9, iso: 'hr' },
  { code: '+53', name: 'Cuba', maxLength: 8, iso: 'cu' },
  { code: '+599', name: 'Curaçao', maxLength: 7, iso: 'cw' },
  { code: '+357', name: 'Cyprus', maxLength: 8, iso: 'cy' },
  { code: '+420', name: 'Czech Republic', maxLength: 9, iso: 'cz' },
  { code: '+45', name: 'Denmark', maxLength: 8, iso: 'dk' },
  { code: '+253', name: 'Djibouti', maxLength: 8, iso: 'dj' },
  { code: '+1-767', name: 'Dominica', maxLength: 7, iso: 'dm' },
  { code: '+1-809', name: 'Dominican Republic', maxLength: 7, iso: 'do' },
  { code: '+670', name: 'East Timor', maxLength: 8, iso: 'tl' },
  { code: '+593', name: 'Ecuador', maxLength: 9, iso: 'ec' },
  { code: '+20', name: 'Egypt', maxLength: 10, iso: 'eg' },
  { code: '+503', name: 'El Salvador', maxLength: 8, iso: 'sv' },
  { code: '+240', name: 'Equatorial Guinea', maxLength: 9, iso: 'gq' },
  { code: '+291', name: 'Eritrea', maxLength: 7, iso: 'er' },
  { code: '+372', name: 'Estonia', maxLength: 8, iso: 'ee' },
  { code: '+251', name: 'Ethiopia', maxLength: 9, iso: 'et' },
  { code: '+500', name: 'Falkland Islands', maxLength: 5, iso: 'fk' },
  { code: '+298', name: 'Faroe Islands', maxLength: 6, iso: 'fo' },
  { code: '+679', name: 'Fiji', maxLength: 7, iso: 'fj' },
  { code: '+358', name: 'Finland', maxLength: 9, iso: 'fi' },
  { code: '+33', name: 'France', maxLength: 9, iso: 'fr' },
  { code: '+594', name: 'French Guiana', maxLength: 9, iso: 'gf' },
  { code: '+689', name: 'French Polynesia', maxLength: 6, iso: 'pf' },
  { code: '+241', name: 'Gabon', maxLength: 8, iso: 'ga' },
  { code: '+220', name: 'Gambia', maxLength: 7, iso: 'gm' },
  { code: '+995', name: 'Georgia', maxLength: 9, iso: 'ge' },
  { code: '+49', name: 'Germany', maxLength: 11, iso: 'de' },
  { code: '+233', name: 'Ghana', maxLength: 9, iso: 'gh' },
  { code: '+350', name: 'Gibraltar', maxLength: 8, iso: 'gi' },
  { code: '+30', name: 'Greece', maxLength: 10, iso: 'gr' },
  { code: '+299', name: 'Greenland', maxLength: 6, iso: 'gl' },
  { code: '+1-473', name: 'Grenada', maxLength: 7, iso: 'gd' },
  { code: '+590', name: 'Guadeloupe', maxLength: 9, iso: 'gp' },
  { code: '+1-671', name: 'Guam', maxLength: 7, iso: 'gu' },
  { code: '+502', name: 'Guatemala', maxLength: 8, iso: 'gt' },
  { code: '+224', name: 'Guinea', maxLength: 9, iso: 'gn' },
  { code: '+245', name: 'Guinea-Bissau', maxLength: 7, iso: 'gw' },
  { code: '+592', name: 'Guyana', maxLength: 7, iso: 'gy' },
  { code: '+509', name: 'Haiti', maxLength: 8, iso: 'ht' },
  { code: '+504', name: 'Honduras', maxLength: 8, iso: 'hn' },
  { code: '+852', name: 'Hong Kong', maxLength: 8, iso: 'hk' },
  { code: '+36', name: 'Hungary', maxLength: 9, iso: 'hu' },
  { code: '+354', name: 'Iceland', maxLength: 7, iso: 'is' },
  { code: '+91', name: 'India', maxLength: 10, iso: 'in' },
  { code: '+62', name: 'Indonesia', maxLength: 11, iso: 'id' },
  { code: '+98', name: 'Iran', maxLength: 10, iso: 'ir' },
  { code: '+964', name: 'Iraq', maxLength: 10, iso: 'iq' },
  { code: '+353', name: 'Ireland', maxLength: 9, iso: 'ie' },
  { code: '+972', name: 'Israel', maxLength: 9, iso: 'il' },
  { code: '+39', name: 'Italy', maxLength: 10, iso: 'it' },
  { code: '+1-876', name: 'Jamaica', maxLength: 7, iso: 'jm' },
  { code: '+81', name: 'Japan', maxLength: 10, iso: 'jp' },
  { code: '+962', name: 'Jordan', maxLength: 9, iso: 'jo' },
  { code: '+7', name: 'Kazakhstan', maxLength: 10, iso: 'kz' },
  { code: '+254', name: 'Kenya', maxLength: 9, iso: 'ke' },
  { code: '+686', name: 'Kiribati', maxLength: 8, iso: 'ki' },
  { code: '+965', name: 'Kuwait', maxLength: 8, iso: 'kw' },
  { code: '+996', name: 'Kyrgyzstan', maxLength: 9, iso: 'kg' },
  { code: '+856', name: 'Laos', maxLength: 9, iso: 'la' },
  { code: '+371', name: 'Latvia', maxLength: 8, iso: 'lv' },
  { code: '+961', name: 'Lebanon', maxLength: 8, iso: 'lb' },
  { code: '+266', name: 'Lesotho', maxLength: 8, iso: 'ls' },
  { code: '+231', name: 'Liberia', maxLength: 8, iso: 'lr' },
  { code: '+218', name: 'Libya', maxLength: 9, iso: 'ly' },
  { code: '+423', name: 'Liechtenstein', maxLength: 7, iso: 'li' },
  { code: '+370', name: 'Lithuania', maxLength: 8, iso: 'lt' },
  { code: '+352', name: 'Luxembourg', maxLength: 9, iso: 'lu' },
  { code: '+853', name: 'Macao', maxLength: 8, iso: 'mo' },
  { code: '+389', name: 'Macedonia', maxLength: 8, iso: 'mk' },
  { code: '+261', name: 'Madagascar', maxLength: 9, iso: 'mg' },
  { code: '+265', name: 'Malawi', maxLength: 9, iso: 'mw' },
  { code: '+60', name: 'Malaysia', maxLength: 10, iso: 'my' },
  { code: '+960', name: 'Maldives', maxLength: 7, iso: 'mv' },
  { code: '+223', name: 'Mali', maxLength: 8, iso: 'ml' },
  { code: '+356', name: 'Malta', maxLength: 8, iso: 'mt' },
  { code: '+692', name: 'Marshall Islands', maxLength: 7, iso: 'mh' },
  { code: '+596', name: 'Martinique', maxLength: 9, iso: 'mq' },
  { code: '+222', name: 'Mauritania', maxLength: 8, iso: 'mr' },
  { code: '+230', name: 'Mauritius', maxLength: 8, iso: 'mu' },
  { code: '+262', name: 'Mayotte', maxLength: 9, iso: 'yt' },
  { code: '+52', name: 'Mexico', maxLength: 10, iso: 'mx' },
  { code: '+691', name: 'Micronesia', maxLength: 7, iso: 'fm' },
  { code: '+373', name: 'Moldova', maxLength: 8, iso: 'md' },
  { code: '+377', name: 'Monaco', maxLength: 8, iso: 'mc' },
  { code: '+976', name: 'Mongolia', maxLength: 8, iso: 'mn' },
  { code: '+382', name: 'Montenegro', maxLength: 8, iso: 'me' },
  { code: '+1-664', name: 'Montserrat', maxLength: 7, iso: 'ms' },
  { code: '+212', name: 'Morocco', maxLength: 9, iso: 'ma' },
  { code: '+258', name: 'Mozambique', maxLength: 9, iso: 'mz' },
  { code: '+95', name: 'Myanmar', maxLength: 9, iso: 'mm' },
  { code: '+264', name: 'Namibia', maxLength: 9, iso: 'na' },
  { code: '+674', name: 'Nauru', maxLength: 7, iso: 'nr' },
  { code: '+977', name: 'Nepal', maxLength: 10, iso: 'np' },
  { code: '+31', name: 'Netherlands', maxLength: 9, iso: 'nl' },
  { code: '+687', name: 'New Caledonia', maxLength: 6, iso: 'nc' },
  { code: '+64', name: 'New Zealand', maxLength: 9, iso: 'nz' },
  { code: '+505', name: 'Nicaragua', maxLength: 8, iso: 'ni' },
  { code: '+227', name: 'Niger', maxLength: 8, iso: 'ne' },
  { code: '+234', name: 'Nigeria', maxLength: 10, iso: 'ng' },
  { code: '+683', name: 'Niue', maxLength: 4, iso: 'nu' },
  { code: '+672', name: 'Norfolk Island', maxLength: 6, iso: 'nf' },
  { code: '+850', name: 'North Korea', maxLength: 9, iso: 'kp' },
  { code: '+1-670', name: 'Northern Mariana Islands', maxLength: 7, iso: 'mp' },
  { code: '+47', name: 'Norway', maxLength: 8, iso: 'no' },
  { code: '+968', name: 'Oman', maxLength: 8, iso: 'om' },
  { code: '+92', name: 'Pakistan', maxLength: 10, iso: 'pk' },
  { code: '+680', name: 'Palau', maxLength: 7, iso: 'pw' },
  { code: '+970', name: 'Palestine', maxLength: 9, iso: 'ps' },
  { code: '+507', name: 'Panama', maxLength: 8, iso: 'pa' },
  { code: '+675', name: 'Papua New Guinea', maxLength: 8, iso: 'pg' },
  { code: '+595', name: 'Paraguay', maxLength: 9, iso: 'py' },
  { code: '+51', name: 'Peru', maxLength: 9, iso: 'pe' },
  { code: '+63', name: 'Philippines', maxLength: 10, iso: 'ph' },
  { code: '+48', name: 'Poland', maxLength: 9, iso: 'pl' },
  { code: '+351', name: 'Portugal', maxLength: 9, iso: 'pt' },
  { code: '+1-787', name: 'Puerto Rico', maxLength: 7, iso: 'pr' },
  { code: '+974', name: 'Qatar', maxLength: 8, iso: 'qa' },
  { code: '+262', name: 'Réunion', maxLength: 9, iso: 're' },
  { code: '+40', name: 'Romania', maxLength: 9, iso: 'ro' },
  { code: '+7', name: 'Russia', maxLength: 10, iso: 'ru' },
  { code: '+250', name: 'Rwanda', maxLength: 9, iso: 'rw' },
  { code: '+590', name: 'Saint Barthélemy', maxLength: 9, iso: 'bl' },
  { code: '+290', name: 'Saint Helena', maxLength: 4, iso: 'sh' },
  { code: '+1-869', name: 'Saint Kitts and Nevis', maxLength: 7, iso: 'kn' },
  { code: '+1-758', name: 'Saint Lucia', maxLength: 7, iso: 'lc' },
  { code: '+590', name: 'Saint Martin', maxLength: 9, iso: 'mf' },
  { code: '+508', name: 'Saint Pierre and Miquelon', maxLength: 6, iso: 'pm' },
  { code: '+1-784', name: 'Saint Vincent and the Grenadines', maxLength: 7, iso: 'vc' },
  { code: '+685', name: 'Samoa', maxLength: 7, iso: 'ws' },
  { code: '+378', name: 'San Marino', maxLength: 10, iso: 'sm' },
  { code: '+239', name: 'Sao Tome and Principe', maxLength: 7, iso: 'st' },
  { code: '+966', name: 'Saudi Arabia', maxLength: 9, iso: 'sa' },
  { code: '+221', name: 'Senegal', maxLength: 9, iso: 'sn' },
  { code: '+381', name: 'Serbia', maxLength: 9, iso: 'rs' },
  { code: '+248', name: 'Seychelles', maxLength: 7, iso: 'sc' },
  { code: '+232', name: 'Sierra Leone', maxLength: 8, iso: 'sl' },
  { code: '+65', name: 'Singapore', maxLength: 8, iso: 'sg' },
  { code: '+421', name: 'Slovakia', maxLength: 9, iso: 'sk' },
  { code: '+386', name: 'Slovenia', maxLength: 8, iso: 'si' },
  { code: '+677', name: 'Solomon Islands', maxLength: 7, iso: 'sb' },
  { code: '+252', name: 'Somalia', maxLength: 9, iso: 'so' },
  { code: '+27', name: 'South Africa', maxLength: 9, iso: 'za' },
  { code: '+82', name: 'South Korea', maxLength: 10, iso: 'kr' },
  { code: '+34', name: 'Spain', maxLength: 9, iso: 'es' },
  { code: '+94', name: 'Sri Lanka', maxLength: 9, iso: 'lk' },
  { code: '+249', name: 'Sudan', maxLength: 9, iso: 'sd' },
  { code: '+597', name: 'Suriname', maxLength: 7, iso: 'sr' },
  { code: '+268', name: 'Swaziland', maxLength: 8, iso: 'sz' },
  { code: '+46', name: 'Sweden', maxLength: 9, iso: 'se' },
  { code: '+41', name: 'Switzerland', maxLength: 9, iso: 'ch' },
  { code: '+963', name: 'Syria', maxLength: 9, iso: 'sy' },
  { code: '+886', name: 'Taiwan', maxLength: 9, iso: 'tw' },
  { code: '+992', name: 'Tajikistan', maxLength: 9, iso: 'tj' },
  { code: '+255', name: 'Tanzania', maxLength: 9, iso: 'tz' },
  { code: '+66', name: 'Thailand', maxLength: 9, iso: 'th' },
  { code: '+228', name: 'Togo', maxLength: 8, iso: 'tg' },
  { code: '+690', name: 'Tokelau', maxLength: 4, iso: 'tk' },
  { code: '+676', name: 'Tonga', maxLength: 7, iso: 'to' },
  { code: '+1-868', name: 'Trinidad and Tobago', maxLength: 7, iso: 'tt' },
  { code: '+216', name: 'Tunisia', maxLength: 8, iso: 'tn' },
  { code: '+90', name: 'Turkey', maxLength: 10, iso: 'tr' },
  { code: '+993', name: 'Turkmenistan', maxLength: 8, iso: 'tm' },
  { code: '+1-649', name: 'Turks and Caicos Islands', maxLength: 7, iso: 'tc' },
  { code: '+688', name: 'Tuvalu', maxLength: 6, iso: 'tv' },
  { code: '+256', name: 'Uganda', maxLength: 9, iso: 'ug' },
  { code: '+380', name: 'Ukraine', maxLength: 9, iso: 'ua' },
  { code: '+971', name: 'United Arab Emirates', maxLength: 9, iso: 'ae' },
  { code: '+44', name: 'United Kingdom', maxLength: 10, iso: 'gb' },
  { code: '+1', name: 'United States', maxLength: 10, iso: 'us' },
  { code: '+598', name: 'Uruguay', maxLength: 9, iso: 'uy' },
  { code: '+998', name: 'Uzbekistan', maxLength: 9, iso: 'uz' },
  { code: '+678', name: 'Vanuatu', maxLength: 7, iso: 'vu' },
  { code: '+58', name: 'Venezuela', maxLength: 10, iso: 've' },
  { code: '+84', name: 'Vietnam', maxLength: 9, iso: 'vn' },
  { code: '+681', name: 'Wallis and Futuna', maxLength: 6, iso: 'wf' },
  { code: '+967', name: 'Yemen', maxLength: 9, iso: 'ye' },
  { code: '+260', name: 'Zambia', maxLength: 9, iso: 'zm' },
  { code: '+263', name: 'Zimbabwe', maxLength: 9, iso: 'zw' },
];
